[package]
name = "verbiste-rust"
version = "0.1.0"
edition = "2024"

[dependencies]
log = "0.4"
pretty_env_logger = "0.5"
tokio = { version = "1", features = ["full"] }
warp = { version = "0.4", features = ["server"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
